"""empty message

Revision ID: 40ef728fb626
Revises: 9047adb004d5
Create Date: 2022-02-24 17:58:03.745394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ef728fb626'
down_revision = '9047adb004d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('flats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'flats')
    # ### end Alembic commands ###
