"""empty message

Revision ID: 9b447e8f11f4
Revises: 40ef728fb626
Create Date: 2022-02-25 10:38:59.618786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b447e8f11f4'
down_revision = '40ef728fb626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    op.drop_table('expense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name='expense_community_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='expense_pkey')
    )
    op.create_table('incident',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], name='incident_community_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incident_pkey')
    )
    # ### end Alembic commands ###
