"""empty message

Revision ID: c000c79d1b2f
Revises: c3c2606654c3
Create Date: 2022-02-23 18:16:58.078323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c000c79d1b2f'
down_revision = 'c3c2606654c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'user', 'roles', ['role_name'], ['role_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_name')
    # ### end Alembic commands ###
